version: 2

models:
  - name: customer
    description: "A table containing customer information"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: first_name
        description: "The customer's first name"
      - name: last_name
        description: "The customer's last name"
      - name: order_id
        description: "The ID of the order associated with the customer"
      - name: order_date
        description: "The date of the order associated with the customer"
      - name: status
        description: "The status of the order associated with the customer"
  - name: stadium_analysis
    description: "A table containing cleaned stadium data"
    columns:
      - name: id
        description: "The unique identifier for the stadium"
      - name: name
        description: "The name of the stadium"
      - name: city
        description: "The city where the stadium is located"
      - name: capacity
        description: "The seating capacity of the stadium"
      - name: country
        description: "The country where the stadium is located"
      - name: events_hosted
        description: "The number of events hosted by the stadium"
