version: 2

models:
  - name: customer
    description: A table containing customer information
    columns:
      - name: id
        description: The primary key for this table
        data_tests:
          - unique
          - not_null
      - name: first_name
        description: The customer's first name
        data_tests:
          - not_null
      - name: last_name
        description: The customer's last name
        data_tests:
          - not_null
      - name: order_id
        description: The ID of the order associated with the customer
      - name: order_date
        description: The date of the order associated with the customer
      - name: status
        description: The status of the order associated with the customer
        data_tests:
          - not_null
  - name: stadium_analysis
    description: A table containing cleaned stadium data
    columns:
      - name: stadium
        description: Name of the stadium.
      - name: city
        description: City where the stadium is located.
      - name: capacity
        description: Seating capacity of the stadium.
      - name: country
        description: Country where the stadium is located.
      - name: region
        description: Region of the country.
      - name: rank
        description: Rank or importance of the stadium.
      - name: images
        description: Image URLs or references for the stadium.
      - name: home_team
        description: Primary team that plays in the stadium.
      - name: location
        description: Geographical location or coordinates of the stadium.