
version: 2

models:
  - name: customer
    description: "A table containing customer information"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: first_name
        description: "The customer's first name"
      - name: last_name
        description: "The customer's last name"
      - name: order_id
        description: "The ID of the order associated with the customer"
      - name: order_date
        description: "The date of the order associated with the customer"
      - name: status
        description: "The status of the order associated with the customer"
